input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [type] == "django_log" {
    mutate {
      add_field => { "service" => "digital_locker" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "digital-locker-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
